### ISSUE TITLE
NullReferenceException during jobs sending

### ISSUE THREAD

**Issue by dermeister0** [dermeister0/TimesheetParser#21]
![2017-05-18_2214](https://cloud.githubusercontent.com/assets/4054844/26209606/7aecaa34-3c17-11e7-87ef-6f6c1b1f4a66.png)

**Comment by dermeister0** [comment]
```
System.NullReferenceException: Object reference not set to an instance of an object.

   at TimesheetParser.Business.ViewModel.MainViewModel.<SubmitJobs_Executed>d__56.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
